### PR TITLE
Add support for Unstoppable Domains

### PR DESCRIPTION
**Pull request by mikeymop**
Reopening [!1465](https://github.com/Emurgo/yoroi-mobile/pull/1465)

This has the appropriate changes based against the latest code on `develop` and resolves the aforementioned merge conflicts.

In `src/legacy/components/Send/SendScreen.js`:

Add `addressInput` to track the address the user entered
If `addressInput` contains a domain update this.state.address with the resolved address
If `addressInput` is an invalid address, or the domain fails to resolve an address show 'Invalid Address' error
Added logic to resolve Unstoppable domains in `src/legacy/utils/validators.js`

Some examples of the domain error messages on the newer `SendScreen.js`

### CODE REVIEW

**Comment by stackchain** [comment]
hey, @mikeymop, planning to merge it this week for the release 4.5.0 could explain the steps to test it, happy and sad path? @Nebyt

**Comment by mikeymop** [comment]
Hey @stackchain, thanks for helping push this along.

I use `brad.crypto` to test resolution for a valid address.
To test for the individual errors I use some of my own personal domains that are not registered / have no Cardano address bound  yet.

I reached out to the Unstoppable team to see if any test domains can be pinned for unit testing.
Maybe @derain can offer some insight?

Will update you with Unstoppable's response as soon as I get one.

**Comment by nbelthan** [comment]
@stackchain Here's a few domains you can use for testing: 
Happy path: 0xchris.nft brad.crypto 
Unhappy/sad path: 0xchris.dao neverselling.wallet mago.crypto 0xjim.crypto zayi.crypto karimkanso.crypto

**Comment by nbelthan** [comment]
@stackchain could you confirm if you were able to test with the domains we provided?
Could you merge for release 4.5.0 this week?

**Comment by mikeymop** [comment]
Saw this fell behind again. I'll do another merge tonight. Busy week for both of us 😵‍💫

**Comment by Nebyt** [comment]
Hi @mikeymop!
While I was checking your PR I met several issues.
1. It is necessary to add the package `@unstoppabledomains/resolution` into the `./package.json`.
Something like that `"@unstoppabledomains/resolution": "^6.0.0",`
The next issue maybe is the only my problem, but still.
After installing dependencies it was necessary to edit the file `./node_modules/@unstoppabledomains/resolution/build/package.json`
and here
```
    "main": "./build/index.js",
    "directories": {
        "doc": "docs"
    },
    "types": "./build/index.d.ts",
```
delete the `build` folder from paths.

**Edit.**
Please pull the latest changes from the `develop` because it contains fixes for the testnet API.

**Comment by mikeymop** [comment]
@Nebyt Can confirm, this isn't an issue with v5.0.2 which I was building with. It seems v6.0.0 just recently launched as Unstoppable is just about to launch their layer-2 and v6.0.0 appears to have been released in tandem with their layer 2.

I just merged the latest upstream changes and added `v5.0.2` to the package.json. Would you mind testing with this version until I can get word back from Unstoppable?

@DeRain can you lend any insight into the errors that are produced with v6.0.0?

**Comment by Nebyt** [comment]
@mikeymop I have checked the happy path and I have gotten this:
 

I am using the testnet.

**Comment by Nebyt** [comment]
@mikeymop I have checked on the mainnet. And it works as described. Please, don't pay attention to the comment above.
@stackchain

**Review by stackchain — APPROVED** [review]

**Comment by wolverineks** [comment]
@mikeymop did you ever set up a testnet handle?

**Pull request merged**
