### PR TITLE
fix: Update limit price on refresh

### PR DESCRIPTION
**Pull request by jorbuedo**
https://emurgo.atlassian.net/browse/YOMO-799?focusedCommentId=18108

https://emurgo.atlassian.net/browse/YOMO-811

### CODE REVIEW

**Review by SorinC6 — COMMENTED** [review]
@jorbuedo  have tried locally and something seems of as is not updating the price 🤔 have added more logic on this issue in https://github.com/Emurgo/yoroi/pull/2722

**Comment by stackchain** [comment]
> @jorbuedo have tried locally and something seems of as is not updating the price 🤔 have added more logic on this issue in #2722

@SorinC6 @jorbuedo I've brought the changes

**Comment by jorbuedo** [comment]
@SorinC6 @stackchain pretty sure https://github.com/Emurgo/yoroi/pull/2722 is wrong
```
asQuantity(formattedValue)
```
Is not ok. Formatted value can't be passed to asQuantity.

```
<AmountInput onChange={onChange} value={createOrder.limitPrice} editable={!disabled} />
```
createOrder.limitPrice is not directly assignable to the input


And

```
    {
      onSuccess: (poolList: Swap.Pool[]) => {
        const bestPool: Swap.Pool | undefined = poolList
          .sort((a: Swap.Pool, b: Swap.Pool) => a.price - b.price)
          .find(() => true)
        if (bestPool !== undefined) {
          const defaultPrice = createOrder.marketPrice
          const formattedValue = BigNumber(defaultPrice).decimalPlaces(PRECISION).toFormat(numberLocale)
          selectedPoolChanged(bestPool)
          limitPriceChanged(asQuantity(formattedValue))
        }
      },
    },
```
    
   
None of that should be modified from here. The pool change is already done on createOrder, and again limitPriceChanged can't receive that.

**Comment by jorbuedo** [comment]
@stackchain now it should work

**Comment by jorbuedo** [comment]
Passing tests, the ultimate frontier

**Comment by jorbuedo** [comment]
fixes https://emurgo.atlassian.net/browse/YOMO-811 as well

**Review by stackchain — APPROVED** [review]

**Pull request merged**
