### PR TITLE
chore(wallet-mobile): bumped cardano-hw-app ledger 7.x

### PR DESCRIPTION
**Pull request by stackchain**
##### Ticket

YOMO-1743

> [!NOTE]
> Please create the ticket if missing it.

### CODE REVIEW

**Review by banklesss — APPROVED** [review]

**Review by michalszorad — APPROVED** [review]

**Comment by stackchain** [comment]
@michaeljscript can you bump `yoroi-lib` ?

**Comment by michalszorad** [comment]
@stackchain I'm having a look

**Comment by michalszorad** [comment]
https://github.com/Emurgo/yoroi-lib/pull/145 is in review

**Comment by michalszorad** [comment]
yoroi lib [0.15.6](https://www.npmjs.com/package/@emurgo/yoroi-lib/v/0.15.6) is released

**Pull request merged**
