### PR TITLE
hotfix(wallet-mobile): Update CSL and yoroi-lib to support hardfork changes

### PR DESCRIPTION
**Pull request by michalszorad**
## Description / Change(s) / Related issue(s)

Update CSL and yoroi-lib to support hardfork changes

##### Ticket

[YOMO-1883](https://emurgo.atlassian.net/jira/software/c/projects/YOMO/issues/YOMO-1883)
[YOMO-1904](https://emurgo.atlassian.net/browse/YOMO-1904)

[YOMO-1883]: https://emurgo.atlassian.net/browse/YOMO-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[YOMO-1904]: https://emurgo.atlassian.net/browse/YOMO-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by michalszorad** [comment]
Getting nonsense eslint errors such as the following even though the async/await is correct. Trying to fix this.

```
/Users/michalszorad/Desktop/yoroi/node_modules/typescript/lib/tsc.js:117341
      throw e;
      ^

Error: Debug Failure. No error for last overload signature
    at resolveCall (/Users/michalszorad/Desktop/yoroi/node_modules/typescript/lib/tsc.js:71249:19)

```
error 2
```
Error: Debug Failure. No error for last overload signature
Occurred while linting /Users/michalszorad/Desktop/yoroi/apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.test.ts:71
Rule: "@typescript-eslint/await-thenable"
```

**Comment by stackchain** [comment]
> Getting nonsense eslint errors such as the following even though the async/await is correct. Trying to fix this.
> 
> ```
> /Users/michalszorad/Desktop/yoroi/node_modules/typescript/lib/tsc.js:117341
>       throw e;
>       ^
> 
> Error: Debug Failure. No error for last overload signature
>     at resolveCall (/Users/michalszorad/Desktop/yoroi/node_modules/typescript/lib/tsc.js:71249:19)
> ```
> 
> error 2
> 
> ```
> Error: Debug Failure. No error for last overload signature
> Occurred while linting /Users/michalszorad/Desktop/yoroi/apps/wallet-mobile/src/yoroi-wallets/cardano/getMinAmounts.test.ts:71
> Rule: "@typescript-eslint/await-thenable"
> ```

did you `yarn reset`?

**Comment by michalszorad** [comment]
The issue was the types were not matching the types we used in yoroi lib and the ts crashed while validating types. https://github.com/microsoft/TypeScript/issues/35186

**Comment by michalszorad** [comment]
Confirmed swap working in this branch.
Screenshot 2024-09-04 at 13 35 29

**Comment by michalszorad** [comment]
Doing a couple of more tests

**Comment by michalszorad** [comment]
Cancelling open order works as well

**Review by jorbuedo — APPROVED** [review]

**Comment by stackchain** [comment]
ty @michaeljscript preparering the hot fix

**Review by banklesss — APPROVED** [review]

**Comment by stackchain** [comment]
Closing in favour of #3597 (release-branch)

**Pull request closed without merging**
