### PR TITLE
add !!! to default messages

### PR DESCRIPTION
**Pull request by wolverineks**

### CODE REVIEW

**Review by zuzunker — COMMENTED** [review]
@wolverineks , looks good, but a question: have you also checked that these default messages are not being displayed at the moment?

**Comment by wolverineks** [comment]
no, I'll do that today

**Comment by wolverineks** [comment]
@vsubhuman done

**Review by zuzunker — APPROVED** [review]

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
