### PR TITLE
Hotfix staking order

### PR DESCRIPTION
**Pull request by stackchain**
- New backend is delivering the certificates in a nondeterministic order

### CODE REVIEW

**Review by banklesss — APPROVED** [review]

**Comment by stackchain** [comment]
To get the delegation status the time complexity is always O(n log n) sorting + O(n) searching, if we revert the order by `submittedAt` and return after finding the first tx with the same reward address, the search can become eventually ~O(1), if we filter after sorting for same reward address, searching will be most likely O(1)

**Comment by pedromtcosta** [comment]
This commit fixes the order on the backend: https://github.com/Emurgo/yoroi-graphql-migration-backend/commit/f83f23ebf9ebaa72cf373d974b47a0b74ca4d564

is this PR still relevant after the fix on the backend?

**Comment by stackchain** [comment]
> This commit fixes the order on the backend: [Emurgo/yoroi-graphql-migration-backend@f83f23e](https://github.com/Emurgo/yoroi-graphql-migration-backend/commit/f83f23ebf9ebaa72cf373d974b47a0b74ca4d564)
> 
> is this PR still relevant after the fix on the backend?

@pedromtcosta, txs are cached locally on mobile, resync will rehydrate the cache with the new response from the backend, but this will require the user to perform some action. 🤔

**Comment by stackchain** [comment]
closing in favor of the update done in the backend.

**Pull request closed without merging**
