### PR TITLE
fix(wallet-mobile): remove duplicate title

### PR DESCRIPTION
**Pull request by jorbuedo**
##### Ticket

[YOMO-1899](https://emurgo.atlassian.net/browse/YOMO-1899?focusedCommentId=25300)

[YOMO-1899]: https://emurgo.atlassian.net/browse/YOMO-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by banklesss — APPROVED** [review]

**Comment by rahulnr7** [comment]
@jorbuedo the button label for disabled USB has default message with !!!.

**Comment by stackchain** [comment]
USB should be listed only for Android, on iOS is not possible to use USB.

**Comment by rahulnr7** [comment]
Please note the '!!!' chars before the 'Connect with USB'

**Comment by stackchain** [comment]
> Please note the '!!!' chars before the 'Connect with USB'

Yap it means that the translation key was not found.

**Comment by rahulnr7** [comment]
Also had to revert this [change](https://github.com/Emurgo/yoroi/pull/3655/files#:~:text=shelleyTheme%20%3D-,true,-%2C)  to fix below issue

**Comment by jorbuedo** [comment]
Ok

**Pull request merged**
