### PR TITLE
Denis/revive detox

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by banklesss — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
run_detox

**Review by Nebyt — COMMENTED** [review]
run_detox

**Comment by stackchain** [comment]
closing in favour of #2540

**Pull request closed without merging**
