### PR TITLE
fix(catalyst): last step

### PR DESCRIPTION
**Pull request by banklesss**
## Description / Change(s) / Related issue(s)

Re-removing back button in the last catalyst step (summary).

### CODE REVIEW

**Comment by stackchain** [comment]
it shouldn't have the back button, cuz the user already paid for the tx, it is like the summary after the submission

**Comment by banklesss** [comment]
>it shouldn't have the back button, cuz the user already paid for the tx, it is like the summary after the submission

yeah i added the button in the previous PR and i wanted to removed it in this one

bad wording

🤦

**Comment by stackchain** [comment]
> > it shouldn't have the back button, cuz the user already paid for the tx, it is like the summary after the submission
> 
> yeah i added the button in the previous PR and i wanted to removed it in this one
> 
> bad wording
> 
> 🤦

base of the PR is gone I'm guessing, 0 changes :d

**Comment by banklesss** [comment]
@stackchain resurrected

**Review by jorbuedo — APPROVED** [review]

**Pull request merged**
