### PR TITLE
[WIP] Translate to french. 

### PR DESCRIPTION
**Pull request by thibautrey**
- I translated the l10n for french. 
- I changed the path to the terms of use to point to the french one (however I didn't translate that file as I don't have legal expertise in that area)

### CODE REVIEW

**Comment by SebastienGllmt** [comment]
Hey, thanks for the work! We're actually in the middle of changing how our translation system is setup for the mobile app so I'll try my best to get your PR to survive the transition. 

You may be interested in helping to translate https://github.com/Emurgo/yoroi-frontend as we already have a partial French translation and it is much easier to translate. We're hoping to get French fully-translated for the next Chrome version of Yoroi so if you want to help translating it, pls submit your PR as a WIP so we can make sure to avoid duplicate work

**Comment by thibautrey** [comment]
Hi Sebastien, I've seen that you started using Crowdin. I tried to access the project but it seems to be private, so I fallback to manual editing.

**Comment by SebastienGllmt** [comment]
Hey. We've finally gotten around to cleaning up all the translation stuff for Yoroi-Mobile. It'd great if we can add you to the Crowdin page but I need your email. Any way we can get in touch?

**Comment by thibautrey** [comment]
Sure. Hit me up on twitter.com/thibautrey

**Comment by SebastienGllmt** [comment]
I've followed you on Twitter but I can't DM you unless you follow me back (or you change your Twitter settings)

**Comment by v-almonacid** [comment]
Closing as this has already been addressed through crowdin. Thanks for your help @thibautrey !

**Pull request closed without merging**
