### PR TITLE
Upgrade prettier

### PR DESCRIPTION
**Pull request by wolverineks**

### CODE REVIEW

**Review by stackchain — CHANGES_REQUESTED** [review]
There are a few files to adapt, check:
- [ ] `yarn lint`
- [ ] `yarn flow`

**Comment by wolverineks** [comment]
@stackchain 
i dont see any linting or formatting errors on my machine
the flow warnings were introduced by a different PR https://github.com/Emurgo/yoroi-mobile/pull/1448
@vantuz-subhuman said he would investigate

**Review by zuzunker — APPROVED** [review]

**Comment by zuzunker** [comment]
@wolverineks , `yarn lint` gives 19 warnings , see details here: https://github.com/Emurgo/yoroi-mobile/pull/1454/checks?check_run_id=3071294388

In the checks we have the requirements for zero warnings, so gotta fix those. Double-checked on develop - zero warnings there.

Once resolved - we can merge it

**Comment by wolverineks** [comment]
@vantuz-subhuman weird, those errors dont look right. they dont line up with the code i have.
could you check out the branch, yarn, and yarn lint, to confirm?

**Comment by zuzunker** [comment]
> @vantuz-subhuman weird, those errors dont look right. they dont line up with the code i have.
> could you check out the branch, yarn, and yarn lint, to confirm?

hmmmmmmmm, yeah, I don't get any warnings locally tho 🤔 🤔 🤔

**Comment by zuzunker** [comment]
@wolverineks , resolve the conflict file plz and then we'll try to resolve the thing with the lint

**Comment by wolverineks** [comment]
@vantuz-subhuman resolved

**Review by zuzunker — COMMENTED** [review]
/check

**Comment by zuzunker** [comment]
Ah well yeah, all the warnings are happening in the `src/i18n/*` files, so the problem is that when running in check prettier for some reason does NOT ignore the folder, even tho it is in the `.prettierIgnore` file. Investigating

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
