### PR TITLE
Send component container fix

### PR DESCRIPTION
**Pull request by banklesss**
Related to [YOMO-494](https://emurgo.atlassian.net/browse/YOMO-494)

It fixes this 👇🏻

Screenshot 2023-03-17 at 16 01 50

[YOMO-494]: https://emurgo.atlassian.net/browse/YOMO-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by wolverineks** [comment]
what's broken?

**Review by wolverineks — COMMENTED** [review]
tabs already applies safe area bottom

**Comment by banklesss** [comment]
> tabs already applies safe area bottom

exactly. The `bottom` option wasn't before. Now it has the same behaviour as before the change except for the scroll

**Comment by wolverineks** [comment]
> > tabs already applies safe area bottom
> 
> exactly. The `bottom` option wasn't before. Now it has the same behaviour as before the change except for the scroll

screens with tabs should not have bottom safe zones, tabs have that built in

**Comment by banklesss** [comment]
`bottom` was introduced in this commit a98e5033f20c3b4f63fb559c4531bf0b220e08ae

**Review by stackchain — APPROVED** [review]

**Pull request merged**
