### PR TITLE
fix(network-selection): max width wrap

### PR DESCRIPTION
**Pull request by banklesss**
## Description / Change(s) / Related issue(s)

Text was wrapping in some network headers

##### Ticket

YOMO-1816

> [!NOTE]
> Please create the ticket if missing it.

### CODE REVIEW

**Comment by michalszorad** [comment]
For wallets with long names, the back button is blocked, so it can not be clicked on iOS.

Screenshot 2024-08-02 at 23 32 14

**Comment by stackchain** [comment]
@banklesss can you check with Product around the definition for big wallet names, I'd say max 15 with ... (ellipsis)

**Comment by banklesss** [comment]
converted to draft. waiting product decision

**Comment by banklesss** [comment]
Current solution is accepted as provisional @stackchain

**Comment by jorbuedo** [comment]
Trying to come up with a less restrictive solution, I got to https://github.com/Emurgo/yoroi/pull/3489, you can see a video demo there

**Comment by stackchain** [comment]
@banklesss should this one be closed in favour of #3489 ?

**Comment by banklesss** [comment]
> @banklesss should this one be closed in favour of https://github.com/Emurgo/yoroi/pull/3489 ?

yes im going to close it. Later will apply the product decision if its different than these

**Pull request closed without merging**
