### PR TITLE
fix(swap): Remove verified filter, API returns only verified ones

### PR DESCRIPTION
**Pull request by jorbuedo**
related: https://emurgo.atlassian.net/browse/YOMO-759

### CODE REVIEW

**Review by SorinC6 — APPROVED** [review]
@jorbuedo have you checked with product related to removing it? maybe if they will want to show it later we can just hide it until adding our own filters as well 🤔

**Comment by jorbuedo** [comment]
> @jorbuedo have you checked with product related to removing it? maybe if they will want to show it later we can just hide it until adding our own filters as well 🤔

Waiting for answer

**Comment by jorbuedo** [comment]
Looks like no one knows and it's gonna take a while, so I'm adding the `verified` filter to the list just in case the API changes suddenly again to include unverified ones. But assume that's not gonna be the case, so no UI switch to toggle.

**Comment by stackchain** [comment]
in-fact is returning only verified, if they changed it later, we can revert the commit

**Pull request merged**
