### PR TITLE
fix(wallet-mobile): fix app background color

### PR DESCRIPTION
**Pull request by jorbuedo**
##### Ticket

[YOMO-1873](https://emurgo.atlassian.net/browse/YOMO-1873)

[YOMO-1873]: https://emurgo.atlassian.net/browse/YOMO-1873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by banklesss — APPROVED** [review]

**Comment by stackchain** [comment]
@jorbuedo can you check the minimal react-native version?

**Comment by jorbuedo** [comment]
> @jorbuedo can you check the minimal react-native version?

SystemUI is available since expo sdk 49 which is the one we're in: https://docs.expo.dev/versions/v49.0.0/sdk/system-ui/
I installed it with the expo tool and it set the version to 2 something, despite latest being 3 something.
And it's working locally.

So I don't know what's complaining about, I'll try named import instead of *

**Comment by stackchain** [comment]
> > @jorbuedo can you check the minimal react-native version?
> 
> SystemUI is available since expo sdk 49 which is the one we're in: https://docs.expo.dev/versions/v49.0.0/sdk/system-ui/ I installed it with the expo tool and it set the version to 2 something, despite latest being 3 something. And it's working locally.
> 
> So I don't know what's complaining about, I'll try named import instead of *

maybe is jest, then it needs to be added to the ignore pattern, and mocked in the jest setup.

**Comment by jorbuedo** [comment]
> maybe is jest, then it needs to be added to the ignore pattern, and mocked in the jest setup.

Yes, just check, it's jest the one complaining

**Pull request merged**
