### PR TITLE
Updating react-native bindings to latest version 2.0

### PR DESCRIPTION
**Pull request by zuzunker**

### CODE REVIEW

**Comment by wolverineks** [comment]
was `TransactionMetadata` renamed to `AuxiliaryData`?

**Review by wolverineks — CHANGES_REQUESTED** [review]
was 'TransactionMetadata` renamed to `AuxiliaryData`?
if so, all the references in yoroi-mobile need to be updated.
this didnt get caught by flow, because there are no flow types, but there are typescript types

**Review by stackchain — APPROVED** [review]

**Comment by wolverineks** [comment]
@stackchain did you read my review?

**Comment by stackchain** [comment]
> @stackchain did you read my review?

Yap, it was done in alonzo branch, did you find any TransactionMetadata that is still live?

**Comment by zuzunker** [comment]
> was 'TransactionMetadata`renamed to`AuxiliaryData`?
> if so, all the references in yoroi-mobile need to be updated.
> this didnt get caught by flow, because there are no flow types, but there are typescript types

Oh yeah, that's correct, but I thought all of them got handled in this PR: https://github.com/Emurgo/yoroi-mobile/pull/1570

**Comment by wolverineks** [comment]
right, im was looking at an old branch
looks fine

**Pull request merged**
