### PR TITLE
[fix] Loosen promise after hoc removal

### PR DESCRIPTION
**Pull request by stackchain**

### CODE REVIEW

**Review by wolverineks — COMMENTED** [review]
what does this change do?

**Comment by stackchain** [comment]
> what does this change do?

initApp is async.

**Comment by wolverineks** [comment]
@stackchain right, I might be misunderstanding how useEffect/promises work, but it doesn't look like this changes anything. wrapping a promise in another promise? did you notice a change in behavior?

**Comment by stackchain** [comment]
> @stackchain right, I might be misunderstanding how useEffect/promises work, but it doesn't look like this changes anything. wrapping a promise in another promise? did you notice a change in behavior?

React at build time knows that useEffect is sync and keeps throwing warnings, this PR is to remove react's warnings.

**Pull request closed without merging**
