### PR TITLE
fix face id multiple authorization requests

### LINKED ISSUE #1468: Face ID cannot be disabled - ends in infinite loop
https://user-images.githubusercontent.com/22329650/126073699-4ddd796c-cb37-4b2a-94c5-374c58e39438.mov

### PR DESCRIPTION
**Pull request by wolverineks**
closes #1468 
https://app.asana.com/0/1200559875444054/1200699291867698

### CODE REVIEW

**Review by Nebyt — APPROVED** [review]
Checked on the iPhone 11, iOS 15.1. Works fine. Fixed. 🚀

**Comment by zuzunker** [comment]
> Checked on the iPhone 11, iOS 15.1. Works fine. Fixed. 🚀

**Comment by zuzunker** [comment]
@wolverineks , resolve conflicts then please and let's add it to the release 🎉

**Comment by Nebyt** [comment]
@vsubhuman @wolverineks @stackchain Also fixed the same issue with the Touch id.

**Review by stackchain — APPROVED** [review]

**Pull request closed without merging**
