### PR TITLE
fix(wallet-mobile): Fix missing background in ios, maybe

### PR DESCRIPTION
**Pull request by jorbuedo**
##### Ticket

[YOMO-1543
](https://emurgo.atlassian.net/browse/YOMO-1543)
[YOMO-1639](https://emurgo.atlassian.net/browse/YOMO-1639)

Need someone to check it in iOS

[YOMO-1639]: https://emurgo.atlassian.net/browse/YOMO-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by michalszorad** [comment]
Does this PR fixes any transition issues in NFT Gallery? If yes, what needs to be tested on iOS? From the tickets it's not clear

**Comment by banklesss** [comment]
setting up this branch. give me a sec

**Comment by jorbuedo** [comment]
> Does this PR fixes any transition issues in NFT Gallery? If yes, what needs to be tested on iOS? From the tickets it's not clear

According to this comment https://emurgo.atlassian.net/browse/YOMO-1639?focusedCommentId=23925
the issue could be the lack of background color on the screen on top (the one you're transitioning to)

**Comment by michalszorad** [comment]
The transition seems to work well on iOS


https://github.com/user-attachments/assets/de7abdb5-fab3-4cbd-8bbe-8ff002a81168

**Review by michalszorad — APPROVED** [review]

**Comment by banklesss** [comment]
> The transition seems to work well on iOS

Maybe for that specific screen this needs the white background?

**Comment by banklesss** [comment]
Working

image

**Comment by banklesss** [comment]
Working

image

**Review by banklesss — APPROVED** [review]

**Pull request merged**
